name: Makefile CI

on:
  push:
    branches: [ "master", "2023-01-26-no-more-py2" ]
  pull_request:
    branches: [ "master", "2023-01-26-no-more-py2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: configure
#      run: ./configure

#    - name: Install dependencies
#      run: make

    - name: Run unittests
      run: make ci

#    - name: Run distcheck
#      run: make distcheck
